# Generated by Django 4.0.5 on 2022-06-09 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0002_rename_messagemodel_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
