# Generated by Django 4.0.5 on 2022-06-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0003_rename_reciever_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
